build-and-pr-node:
    name: Generate SDKs and create PRs (Node.js)
    runs-on: ubuntu-latest
    env:
      LIBLAB_TOKEN: ${{ secrets.LIBLAB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.LIBLAB_GITHUB_TOKEN }}
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Specify the node version you want to use
      - name: Install liblab
        run: npm install -g liblab
      - name: Start Build
        run: liblab build --skip-validation --approve-docs
      - name: Create PRs to GitHub repos
        run: liblab pr

  build-and-pr-python:
    name: Generate SDKs and create PRs (Python)
    runs-on: ubuntu-latest
    env:
      LIBLAB_TOKEN: ${{ secrets.LIBLAB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.LIBLAB_GITHUB_TOKEN }}
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 # Specify the Python version you want to use
      - name: Install liblab
        run: pip install liblab  # Use pip to install Python packages
      - name: Start Build
        run: liblab build --skip-validation --approve-docs
      - name: Create PRs to GitHub repos
        run: liblab pr
