name: Generate SDKs using liblab

on:
  # Add any other triggers you want here, such as a push to the spec file
  workflow_call:
    workflow_dispatch:

jobs:
  build-and-pr:
    name: Generate SDKs and create PRs
    runs-on: ubuntu-latest
    env:
      LIBLAB_TOKEN: ${{ secrets.LIBLAB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.LIBLAB_GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3"

      - name: Install liblab (Python)
        run: pip install liblab

      - name: Start Build (Python)
        run: liblab build --skip-validation --approve-docs

      - name: Create PRs to GitHub repos (Python)
        run: liblab pr
